### ISSUE TITLE
Bot not deleting its own message

### ISSUE THREAD

**Issue by McSquizzleswag** [modularitygg/ModularPasteBot#3]
Up until some time ago the bot would delete its own message when a user deleted their log/text file, now the bot isn't deleting its message

**Comment by McSquizzleswag** [comment]
Was this fixed?

**Comment by itssimple** [comment]
No, this hasn't been fixed yet.. but I know the solution to the problem!

**Comment by McSquizzleswag** [comment]
Yay!
